protected/models/Content.php
<?php

/**
 * This is the model class for table "tbl_content".
 *
 * The followings are the available columns in table 'tbl_content':
 * @property integer $id
 * @property string $title
 * @property string $title_ar
 * @property string $text
 * @property string $text_ar
 * @property string $image
 * @property integer $active
 * @property integer $type
 * @property integer $order
 * @property string $create_date
 * @property string $update_date
 * @property string $publish_date
 * @property integer $summary_block_id
 *
 * The followings are the available model relations:
 * @property Block[] $blocks
 * @property Block $summaryBlock
 */
class Content extends SuperModel
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_content';
	}

	const TYPE_ARTICLE = 0;
	const TYPE_NEWS = 1;
	const TYPE_EVENT = 2;

	const STATUS_ACTIVE = 1;
	const STATUS_INACTIVE = 0;

	public $primaryImage;


	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, title_ar','required','on'=>'create-news'),
			array('active, type, order, summary_block_id', 'numerical', 'integerOnly'=>true),
			array('publish_date', 'length', 'max'=>45),
			array('primaryImage','file','maxSize'=>2*1024*1024,'maxFiles'=>1,'types'=>'gif,jpg,png','allowEmpty'=>true),

			array('text, text_ar', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, title_ar, text, text_ar, active, type, order, create_date, update_date, publish_date, summary_block_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'blocks' => array(self::HAS_MANY, 'Block', 'content_id'),
			'summaryBlock' => array(self::BELONGS_TO, 'Block', 'summary_block_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
					'id' => Yii::t('content', 'model.label.id'),
					'title' => Yii::t('content', 'model.label.title'),
					'title_ar' => Yii::t('content', 'model.label.title_ar'),
					'text' => Yii::t('content', 'model.label.text'),
					'text_ar' => Yii::t('content', 'model.label.text_ar'),
					'image_id' => Yii::t('content', 'model.label.image'),
					'primaryImage' => Yii::t('content', 'model.label.primary.image.file'),


					'active' => Yii::t('content', 'model.label.active'),
					'type' => Yii::t('content', 'model.label.type'),

					'order' => Yii::t('content', 'model.label.order'),
					'create_date' => Yii::t('content', 'model.label.create_date'),
					'update_date' => Yii::t('content', 'model.label.update_date'),
					'publish_date' => Yii::t('content', 'model.label.publish_date'),
					'summary_block_id' => Yii::t('content', 'model.label.summary_block'),
				);
	}

	public function delete(){

		return parent::delete();
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('title_ar',$this->title_ar,true);
		$criteria->compare('text',$this->text,true);
		$criteria->compare('text_ar',$this->text_ar,true);
		$criteria->compare('image_id',$this->image_id,true);
		$criteria->compare('active',$this->active);
		$criteria->compare('type',$this->type);

		$criteria->compare('publish_date',$this->publish_date,true);


		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>5,
			),
		));
	}

	public static function getContentTypeArray(){
		return array(
			self::TYPE_ARTICLE=>Yii::t('content','model.type.article'),
			self::TYPE_NEWS=>Yii::t('content','model.type.news'),
		);
	}

	public static function getContentTypeUri(){
		return array(
			Yii::app()->createUrl('article/create')=>Yii::t('content','model.type.article'),
			Yii::app()->createUrl('content/newsCreate')=>Yii::t('content','model.type.news'),
		);
	}


	public function getTitle(){
		if(Yii::app()->getLanguage()=="ar"){
			return $this->title_ar;
		}else{
			return $this->title;
		}
	}
	public function getText(){
		if(Yii::app()->getLanguage()=="ar"){
			return $this->text_ar;
		}else{
			return $this->text;
		}
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Content the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ContentController.php
<?php

class ContentController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'postOnly + delete', // we only allow deletion via POST request

            'checkSideBarSubId +index,create',
            'checkAccess',
            'checkAdminAccess',

        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->pageTitle = Yii::t('content', 'page.title.create.content');
        $this->contentTitle = Yii::t('content', 'controller.page.create.content.title');
        //$this->updateImagesListJSONFile();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Content'])) {
            $model = new Content('create');
            $model->attributes = $_POST['Content'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create');
    }


    public function actionNewsCreate()
    {
        $this->pageTitle = Yii::t('content', 'page.title.create.news.content');
        $this->contentTitle = Yii::t('content', 'controller.page.create.news.content.title');

        $newsContentModel = new Content('create-news');
        $blockModel = new Block;

        //Validation Variables
        $newsContentInfoValid = false;
        $blockModelInfoValid = false;
        $primaryImageInfoValid = true;
        $primaryImageExists = false;


        if (isset($_POST['Content']) && isset($_POST['Block'])) {
            // Fill the Content Model
            $newsContentModel->active = Content::STATUS_INACTIVE;
            $newsContentModel->order = 0;
            $newsContentModel->type = Content::TYPE_NEWS;

            $newsContentModel->title = $_POST['Content']['title'];
            $newsContentModel->title_ar = $_POST['Content']['title_ar'];
            $newsContentModel->primaryImage = CUploadedFile::getInstance($newsContentModel, 'primaryImage');

            $blockModel->type = $_POST['Block']['type'];
            // Setup the appropriate Block Model
            switch ($blockModel->type) {
                case Block::TYPE_TEXT_ONLY:
                    $blockModel->setScenario('create-text-only');
                    break;
                case Block::TYPE_IMAGE_ONLY:
                    $blockModel->setScenario('create-image-only');
                    $blockModel->image1 = CUploadedFile::getInstance($blockModel, 'image1');
                    break;
                case Block::TYPE_TEXT_PLUS_ONE_IMAGE:
                    $blockModel->setScenario('create-text-image1');
                    $blockModel->image1 = CUploadedFile::getInstance($blockModel, 'image1');

                    break;
                case Block::TYPE_TEXT_PLUS_TWO_IMAGES:
                    $blockModel->setScenario('create-text-image2');
                    $blockModel->image1 = CUploadedFile::getInstance($blockModel, 'image1');
                    $blockModel->image2 = CUploadedFile::getInstance($blockModel, 'image2');
                    break;
                case Block::TYPE_TEXT_PLUS_THREE_IMAGES:
                    $blockModel->setScenario('create-text-image3');
                    $blockModel->image1 = CUploadedFile::getInstance($blockModel, 'image1');
                    $blockModel->image2 = CUploadedFile::getInstance($blockModel, 'image2');
                    $blockModel->image3 = CUploadedFile::getInstance($blockModel, 'image3');
                    break;
                default:
                    throw new CHttpException(400);
            }
            //Add Block Images and Text
            $blockModel->attributes = $_POST['Block'];
            if (!$blockModel->type == Block::TYPE_IMAGE_ONLY) {
                $blockModel->text = $_POST['Block']['text'];
                $blockModel->text_ar = $_POST['Block']['text_ar'];
            }

            if ($newsContentModel->validate() & $blockModel->validate()) {
                $newsContentInfoValid = true;
                $blockModelInfoValid = true;
                // Add the primary image of the content (if exists)
                $image = new Image('create-for-content');
                if (!is_null($newsContentModel->primaryImage)) {
                    $primaryImageExists = true;
                    $image->active = Image::STATUS_ACTIVE;
                    $image->type = Image::TYPE_NEWS_SPECIFIC;
                    $image->image = $newsContentModel->primaryImage;
                    if ($image->validate(array('image', 'type'))) {
                        $image->url = sha1($image->image->name . uniqid() . time()) . '.' . $image->image->extensionName;
                        $image->name = $newsContentModel->title;
                        $image->name_ar = $newsContentModel->title_ar;
                        $primaryImageInfoValid = $image->validate();

                    }
                }

                // Check if the form is valid

                $valid = $blockModelInfoValid && $primaryImageInfoValid && $newsContentInfoValid;

                if ($valid) {
                    if ($primaryImageExists && $primaryImageInfoValid) {
                        if ($image->image->saveAs(CommonFunctions::IMAGES_PATH . CommonFunctions::NEWS_IMAGES_PATH . $image->url)) {
                            $image->save(false);
                            $newsContentModel->image_id = $image->id;
                            $imageProcessor = new ImageProcessor();
                            $imageProcessor->source_path = CommonFunctions::IMAGES_PATH . CommonFunctions::NEWS_IMAGES_PATH . $image->url;
                            $imageProcessor->target_path = CommonFunctions::IMAGES_PATH . CommonFunctions::NEWS_IMAGES_PATH . CommonFunctions::NEWS_IMAGES_THUMBS_PATH . $image->url;
                            $imageProcessor->resize(334, 251, ZEBRA_IMAGE_BOXED, -1);
                        }
                    }

                    $newsContentModel->save(false);
                    $blockModel->content_id = $newsContentModel->id;
                    $blockModel->save(false);
                    switch ($blockModel->type) {
                        case Block::TYPE_IMAGE_ONLY:
                            $blockModel->addImage('image1', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            break;
                        case Block::TYPE_TEXT_PLUS_ONE_IMAGE:
                            $blockModel->addImage('image1', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            break;
                        case Block::TYPE_TEXT_PLUS_TWO_IMAGES:
                            $blockModel->addImage('image1', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            $blockModel->addImage('image2', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);

                            break;
                        case Block::TYPE_TEXT_PLUS_THREE_IMAGES:
                            $blockModel->addImage('image1', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            $blockModel->addImage('image2', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            $blockModel->addImage('image3', Image::TYPE_NEWS_SPECIFIC, CommonFunctions::NEWS_IMAGES_PATH, CommonFunctions::NEWS_IMAGES_THUMBS_PATH);
                            break;
                    }
                    $this->redirect(array('content/index'));
                }
            }


        }else{
            $this->updateImagesListJSONFile();
        }

        $this->render('news-create', array(
            'newsContentModel' => $newsContentModel,
            'blockModel' => $blockModel,
        ));
    }

    public function renderContentOptions($data, $row)
    {
        $this->renderPartial('partial/content-option', array(
            'data' => $data,
        ), false, false);
    }

    public function actionDelete()
    {
        if (isset($_POST['content_id'])) {
            $contentModelId = intval($_POST['content_id']);
            $contentModel = $this->loadModel($contentModelId);
            switch ($contentModel->type) {
                case Content::TYPE_NEWS:
                    $this->deleteNewsContent($contentModel);
                    break;
                case Content::TYPE_ARTICLE:
                    $this->deleteArticleContent($contentModel);
                    break;
            }
            $this->redirect(array('content/index'));
        }
    }

    public function actionActive()
    {
        if (isset($_POST['content_id'])) {
            $contentModelId = intval($_POST['content_id']);
            $contentModel = $this->loadModel($contentModelId);
            if($contentModel->active==Content::STATUS_ACTIVE){
                $contentModel->active = Content::STATUS_INACTIVE;


            }else if($contentModel->active==Content::STATUS_INACTIVE){
                $contentModel->active = Content::STATUS_ACTIVE;

protected/views/content/_form.php
<?php
/* @var $this ContentController */
/* @var $model Content */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'content-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textArea($model,'title',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'title_ar'); ?>
		<?php echo $form->textArea($model,'title_ar',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'title_ar'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'text'); ?>
		<?php echo $form->textArea($model,'text',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'text'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'text_ar'); ?>
		<?php echo $form->textArea($model,'text_ar',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'text_ar'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'image'); ?>
		<?php echo $form->textArea($model,'image',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'image'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
		<?php echo $form->error($model,'active'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->textField($model,'type'); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'order'); ?>
		<?php echo $form->textField($model,'order'); ?>
		<?php echo $form->error($model,'order'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'create_date'); ?>
		<?php echo $form->textField($model,'create_date'); ?>
		<?php echo $form->error($model,'create_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'update_date'); ?>
		<?php echo $form->textField($model,'update_date'); ?>
		<?php echo $form->error($model,'update_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'publish_date'); ?>
		<?php echo $form->textField($model,'publish_date',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'publish_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'summary_block_id'); ?>
		<?php echo $form->textField($model,'summary_block_id'); ?>
		<?php echo $form->error($model,'summary_block_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/content/_news-create-form.php
<?php
/**
 * Created by PhpStorm.
 * User: 3mkBurhan
 * Date: 7/24/15
 * Time: 4:01 PM
 */

Yii::app()->clientScript->registerScript('creat-news-script','
$("#block-type-dropdown").on("change",function(){
    if($(this).val() == ""){
        $("#add-news-submit-button-container").hide();
        $("#block-form-container").hide();
    }else{
        $("#add-news-submit-button-container").show();
        $("#block-form-container").show();
    }
})
',CClientScript::POS_END);

?>


<div class="form row">
    <div class="col-md-12">
        <?php $form = $this->beginWidget('CActiveForm', array(
            'id' => 'department-form',
            // Please note: When you enable ajax validation, make sure the corresponding
            // controller action is handling ajax validation correctly.
            // There is a call to performAjaxValidation() commented in generated controller code.
            // See class documentation of CActiveForm for details on this.
            'enableAjaxValidation' => false,
            'enableClientValidation' => true,
            'focus' => array($newsContentModel, 'title'),
            'clientOptions' => array(
                'successCssClass' => 'has-success',
                'errorCssClass' => 'has-error',
                'validatingErrorMessage' => '',
                'inputContainer' => '.form-group',
                'afterValidateAttribute' => 'js:function(form, attribute, data, hasError){
                $("#"+attribute.inputID).siblings(".error-sign").hide();
                $("#"+attribute.inputID).siblings(".ok-sign").hide();
                if(hasError){
                    $("#"+attribute.inputID).siblings(".error-sign").show();
                }else {
                    $("#"+attribute.inputID).siblings(".ok-sign").show();
                }
            }',
            ),
            'htmlOptions' => array(
                'role' => 'form',
                'class' => 'form-horizontal',
                'enctype' => 'multipart/form-data',
            ),
        )); ?>
        <?php if($newsContentModel->hasErrors() || $blockModel->hasErrors()):?>
            <div class="errorHandler alert alert-danger no-display" style="display: block;">
                <?php echo $form->errorSummary($newsContentModel);?>
                <?php echo $form->errorSummary($blockModel);?>
            </div>
        <?php endif;?>


        <div class="form-group<?php echo $newsContentModel->hasErrors('title')?' has-error':'';echo !$newsContentModel->hasErrors('title')&&isset($_POST['Content'])?' has-success':''?>">
            <label class="col-sm-2 control-label" for="form-field-2">
                <?php echo $newsContentModel->getAttributeLabel('title'); ?>
                <?php if ($newsContentModel->isAttributeRequired('title')): ?>
                    <?php if(!$newsContentModel->hasErrors('title')&&isset($_POST['Content'])):?>
                        <span class="symbol ok"></span>
                    <?php endif;?>
                    <?php if($newsContentModel->hasErrors('title') || !isset($_POST['Content'])):?>
                        <span class="symbol required"></span>
                    <?php endif;?>
                <?php endif; ?>
            </label>
            <div class="col-sm-9">
                <?php echo $form->textField($newsContentModel,'title',array(
                    'class'=>'form-control',
                ))?>
                <?php if($newsContentModel->hasErrors('title')):?>
                    <span class="help-block"><?php echo $newsContentModel->getError('title');?></span>
                <?php endif;?>
            </div>
        </div>

        <div class="form-group<?php echo $newsContentModel->hasErrors('title_ar')?' has-error':'';echo !$newsContentModel->hasErrors('title_ar')&&isset($_POST['Content'])?' has-success':''?>">
            <label class="col-sm-2 control-label" for="form-field-2">
                <?php echo $newsContentModel->getAttributeLabel('title_ar'); ?>
                <?php if ($newsContentModel->isAttributeRequired('title_ar')): ?>
                    <?php if(!$newsContentModel->hasErrors('title_ar')&&isset($_POST['Content'])):?>
                        <span class="symbol ok"></span>
                    <?php endif;?>
                    <?php if($newsContentModel->hasErrors('title_ar') || !isset($_POST['Content'])):?>
                        <span class="symbol required"></span>
                    <?php endif;?>
                <?php endif; ?>
            </label>
            <div class="col-sm-9">
                <?php echo $form->textField($newsContentModel,'title_ar',array(
                    'class'=>'form-control',
                ))?>
                <?php if($newsContentModel->hasErrors('title_ar')):?>
                    <span class="help-block"><?php echo $newsContentModel->getError('title_ar');?></span>
                <?php endif;?>
            </div>
        </div>

        <div class="form-group<?php echo $newsContentModel->hasErrors('primaryImage')?' has-error':'';?>">
            <label class="col-sm-2 control-label" for="form-field-2">
                <?php echo $newsContentModel->getAttributeLabel('primaryImage'); ?>

            </label>
            <div class="col-sm-9">
                <div class="fileupload fileupload-new" data-provides="fileupload">
                    <div class="fileupload-new thumbnail" style="width: 350px; height: 230px;"><img
                            src="http://www.placehold.it/350x230/EFEFEF/AAAAAA?text=no+image" alt=""/>
                    </div>
                    <div class="fileupload-preview fileupload-exists thumbnail"
                         style="max-width: 200px; max-height: 250px; line-height: 20px;"></div>
                    <div>
														<span class="btn btn-light-grey btn-file"><span
                                                                class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span><span
                                                                class="fileupload-exists"><i
                                                                    class="fa fa-picture-o"></i> Change</span>
                                                            <?php echo $form->fileField($newsContentModel, 'primaryImage', array()); ?>
														</span>
                        <a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
                            <i class="fa fa-times"></i> Remove
                        </a>
                    </div>
                    <?php if($newsContentModel->hasErrors('title_ar')):?>
                        <span class="help-block"><?php echo $newsContentModel->getError('primaryImage');?></span>
                    <?php endif;?>
                </div>
            </div>
        </div>

        <div class="form-group<?php echo $blockModel->hasErrors('type')?' has-error':'';echo !$newsContentModel->hasErrors('type')&&isset($_POST['Content'])?' has-success':''?>">
            <label class="col-sm-2 control-label" for="form-field-2">
                <?php echo $blockModel->getAttributeLabel('type'); ?>
                <?php if(!$blockModel->hasErrors('type')&&isset($_POST['Content'])):?>
                    <span class="symbol ok"></span>
                <?php endif;?>
                <?php if($blockModel->hasErrors('type') || !isset($_POST['Content'])):?>
                    <span class="symbol required"></span>
                <?php endif;?>
            </label>
            <div class="col-sm-9">
                <?php
                echo CHtml::activeDropDownList($blockModel,'type',Block::getBlockTypeArray(),array(
                    'prompt'=>Yii::t('content','select.block.type.message'),
                    'class'=>'form-control',
                    'id'=>'block-type-dropdown',
                    'ajax'=>array(
                        'url'=>$this->createUrl('content/getBlockCreateForm'),
                        'type'=>'GET',
                        'data'=>array(
                            'type'=>'js:$(this).val()',
                        ),
                        'beforeSend'=>'js:function(){
                        }',
                        'success'=>'js:function(data){
                            $("#block-form-container").html(data);
                        }',
                        'error'=>'js:function(){
                        }'
                    ),
                ));
                ?>
                <?php if($blockModel->hasErrors('type')):?>
                    <span class="help-block"><?php echo $blockModel->getError('type');?></span>
                <?php endif;?>
            </div>
        </div>

        <div id="block-form-container" style="display: <?php echo isset($_POST['Content'])?'block':'none';?>;">
            <?php if(isset($_POST['Content'])):?>
                <?php $this->renderPartial('partial/_block-form',array(
                    'blockModel'=>$blockModel,
                ));?>
            <?php endif;?>
        </div>

        <div id="add-news-submit-button-container" style="display: <?php echo isset($_POST['Content'])?'block':'none';?>;">
            <hr/>
            <div class="row">
                <div class="col-md-offset-8 col-md-4">
                    <button class="btn btn-yellow btn-block" type="submit">
                        <?php echo Yii::t('content','controller.content.action.add.news')?> <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </div>
        </div>

        <?php $this->endWidget(); ?>
    </div>
</div><!-- End Form Container-->

protected/views/content/article-create.php
<?php
/**
 * Created by PhpStorm.
 * User: 3mkBurhan
 * Date: 7/24/15
 * Time: 3:17 PM
 */


$this->breadcrumbs=array(
    array(
        'name'=>'Content',
        'url'=>Yii::app()->createUrl('content/index'),
    ),
    array(
        'name'=>'Create',
        'url'=>Yii::app()->createUrl('content/create'),
    ),
    'Create Article',
);

protected/views/content/news-create.php
<?php
/**
 * Created by PhpStorm.
 * User: 3mkBurhan
 * Date: 7/24/15
 * Time: 3:17 PM
 */


$this->breadcrumbs=array(
    array(
        'name'=>'Content',
        'url'=>Yii::app()->createUrl('content/index'),
    ),
    array(
        'name'=>'Create',
        'url'=>Yii::app()->createUrl('content/create'),
    ),
    'Create News',
);


$this->cssAssets[] = 'bootstrap-fileupload.min.css';

$this->jsAssets[] = 'bootstrap-fileupload.min.js';
$this->jsAssets[] = 'ckeditor/ckeditor.js';


Yii::app()->clientScript->registerScript("content-create-script",'
var imagesListJSONFile = '.CJavaScript::encode(Yii::app()->baseUrl."/json/images_list.json").';
',CClientScript::POS_END);

?>
<div class="panel panel-default">
    <div class="panel-body">
        <h2>Add News Item</h2>
        <hr>
        <?php $this->renderPartial('_news-create-form',array(
            'newsContentModel'=>$newsContentModel,
            'blockModel'=>$blockModel,
        ));?>
    </div>
</div>