protected/models/User.php
<?php

/**
 * This is the model class for table "tbl_user".
 *
 * The followings are the available columns in table 'tbl_user':
 * @property integer $id
 * @property string $username
 * @property string $login_name
 * @property string $first_name
 * @property string $last_name
 * @property string $middle_name
 * @property string $email
 * @property string $password
 * @property string $create_date
 * @property integer $create_id
 * @property string $update_date
 * @property integer $update_id
 * @property integer $status
 * @property integer $doctor_id
 */
class User extends SuperModel
{
	/**
	 * @return string the associated database table name
	 */
	const STATUS_ONLINE = 1;
	const STATUS_OFFLINE = 0;
	const STATUS_BREAK = 2;

	const ROLE_ADMIN = 0;
	const ROLE_EDITOR = 1;


	public $role;
	const SALT = "jas#&12a1@(/as";

	public function tableName()
	{
		return 'tbl_user';
	}

	public function getName(){
		return $this->first_name." ".$this->last_name;
	}
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username,login_name,first_name,last_name,password,role', 'required','on'=>'create'),
			array('username,login_name,first_name,last_name,password,role,doctor_id', 'required','on'=>'create-doctor'),
			array('username,login_name, first_name,last_name,role', 'required','on'=>'update'),
			array('username,login_name, first_name,last_name,role,doctor_id', 'required','on'=>'update-editor'),
			array('email,middle_name','safe','on'=>'create'),
			array('email,middle_name','safe','on'=>'update'),
			array('create_id, update_id, status', 'numerical', 'integerOnly'=>true),
			array('username, login_name, first_name, last_name, middle_name, email, password', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, login_name, first_name, last_name, middle_name, email, password, create_date, create_id, update_date, update_id, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('user','model.label.id'),
			'username' => Yii::t('user','model.label.username'),
			'login_name' => Yii::t('user','model.label.login_name'),
			'first_name' => Yii::t('user','model.label.first_name'),
			'last_name' => Yii::t('user','model.label.last_name'),
			'middle_name' => Yii::t('user','model.label.middle_name'),
			'email' => Yii::t('user','model.label.email'),
			'password' => Yii::t('user','model.label.password'),
			'create_date' => Yii::t('user','model.label.create_date'),
			'create_id' => Yii::t('user','model.label.create_id'),
			'update_date' => Yii::t('user','model.label.update_date'),
			'update_id' => Yii::t('user','model.label.update_id'),
			'status' => Yii::t('user','model.label.status'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('login_name',$this->login_name,true);
		$criteria->compare('first_name',$this->first_name,true);
		$criteria->compare('last_name',$this->last_name,true);
		$criteria->compare('middle_name',$this->middle_name,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('create_date',$this->create_date,true);
		$criteria->compare('create_id',$this->create_id);
		$criteria->compare('update_date',$this->update_date,true);
		$criteria->compare('update_id',$this->update_id);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	protected function afterValidate()
	{
		parent::afterValidate();
		if ($this->isNewRecord) {
			$this->password = $this->hashPassword($this->password);
		}
	}

	protected function beforeSave(){
		$this->first_name = strtolower($this->first_name);
		$this->last_name = strtolower($this->last_name);
		$this->middle_name = strtolower($this->middle_name);
		$this->username = strtolower($this->username);
		$this->login_name = strtolower($this->login_name);
		return parent::beforeSave();
	}
	public function hashPassword($password)
	{
		return sha1(self::SALT . $password);

	}
	public function validatePassword($password)
	{
		return $this->password === $this->hashPassword($password);
	}
	/*
	 * ===========================
	 * Getters
	 * ===========================
	 */


	public function getFirstName(){
		return ucwords($this->first_name);
	}
	public function getLastName(){
		return ucwords($this->last_name);
	}
	public function getMiddleName()
	{
		return ucwords($this->middle_name);
	}
	public function getLoginName()
	{
		return $this->login_name;
	}
	public function getUsername()
	{
		return $this->username;
	}
	public function getEmail(){
		return $this->email;
	}

	/*
	 * ===============================
	 * Authentication/Authorization
	 * ===============================
	 */

	public static function getRolesOptionsList()
	{
		return array(
			self::ROLE_ADMIN => 'Admin',
			self::ROLE_EDITOR => 'Doctor',
		);
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkSideBarSubId +index,create',
            'postOnly + delete', // we only allow deletion via POST request
            'checkAccess',
            'checkAdminAccess',
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->pageTitle = Yii::t('user', 'page.title.create.user');
        $this->contentTitle = Yii::t('user', 'controller.page.create.content.title');

        $model = new User('create');
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['User'])) {

            $model->attributes = $_POST['User'];
            $model->status = User::STATUS_OFFLINE;
            if ($model->role == User::ROLE_EDITOR) {
                $model->setScenario('create-doctor');
                if (strlen($_POST['User']['doctor_id']) > 0) {
                    $model->doctor_id = intval($_POST['User']['doctor_id']);
                }else{
                    $model->unsetAttributes(array('doctor_id'));
                }
            }

            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            } else {
                $model->password = "";
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $this->pageTitle = Yii::t('user', 'page.title.update.user');
        $this->contentTitle = Yii::t('user', 'controller.page.update.content.title');

        $model = $this->loadModel($id);
        $model->setScenario('update');
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            if ($model->role == User::ROLE_EDITOR) {
                $model->setScenario('update-editor');
                if (strlen($_POST['User']['doctor_id']) > 0) {
                    $model->doctor_id = intval($_POST['User']['doctor_id']);
                }else{
                    $model->unsetAttributes(array('doctor_id'));
                }
            }
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $this->pageTitle = Yii::t('user', 'Users');
        $this->contentTitleAvailable = true;
        $this->contentTitle = Yii::t('user', 'Users');

        $userModel = new User('search');
        $userModel->unsetAttributes();
        $this->render('index', array(
            'userModel' => $userModel,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new User('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['User']))
            $model->attributes = $_GET['User'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = User::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    public function renderActionCellValue($data, $row)
    {
        echo $this->renderPartial('partials/user-list-action-cell', array(
            'data' => $data,
        ), false, false);
    }

    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */

    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'login_name'); ?>
		<?php echo $form->textField($model,'login_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'first_name'); ?>
		<?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'last_name'); ?>
		<?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'middle_name'); ?>
		<?php echo $form->textField($model,'middle_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_date'); ?>
		<?php echo $form->textField($model,'create_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_id'); ?>
		<?php echo $form->textField($model,'create_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_date'); ?>
		<?php echo $form->textField($model,'update_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_id'); ?>
		<?php echo $form->textField($model,'update_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('login_name')); ?>:</b>
	<?php echo CHtml::encode($data->login_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('first_name')); ?>:</b>
	<?php echo CHtml::encode($data->first_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_name')); ?>:</b>
	<?php echo CHtml::encode($data->last_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('middle_name')); ?>:</b>
	<?php echo CHtml::encode($data->middle_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_date')); ?>:</b>
	<?php echo CHtml::encode($data->create_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_id')); ?>:</b>
	<?php echo CHtml::encode($data->create_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_date')); ?>:</b>
	<?php echo CHtml::encode($data->update_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_id')); ?>:</b>
	<?php echo CHtml::encode($data->update_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	*/ ?>

</div>

protected/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'username',
		'login_name',
		'first_name',
		'last_name',
		'middle_name',
		/*
		'email',
		'password',
		'create_date',
		'create_id',
		'update_date',
		'update_id',
		'status',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	array(
		'name'=>'Users',
		'url'=>Yii::app()->createUrl('user/index'),
	),
	'Create',
);

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl."/js/user-logic.js",CClientScript::POS_END);

$this->renderPartial('_form', array('model'=>$model));

?>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	array(
		'name'=>'Users',
		'url'=>Yii::app()->createUrl('user/index'),
	),
);

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl."/js/user-logic.js",CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->theme->baseUrl."/assets/js/bootstrap-switch.min.js",CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->theme->baseUrl."/assets/css/bootstrap-switch.min.css");

$this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'user-grid',
	'rowHtmlOptionsExpression' => 'array("class"=>"grid-row",
    )',
	'summaryText' => 'User Count: {count}',
	'summaryCssClass' => 'complete-summery',
	'beforeAjaxUpdate'=>'js:function(){
        $("#loading-indicator").show();
    }',
	'afterAjaxUpdate' => 'js:function(){
		$(".Tabled table").addClass("table");
        $(".Tabled table").addClass("table-condensed");
        $(".tooltip-link").tooltip();
	}',
	'htmlOptions' => array(
		'class' => 'Tabled',
	),
	'cssFile' => Yii::app()->baseUrl . '/css/main.css',
	'dataProvider' => $userModel->search(),

	//'filter' => $userModel,
	'columns' => array(
		array(
			'header'=>Yii::t('user','grid.header.action'),
			'value'=>array($this,'renderActionCellValue'),
		),
		array(
			'name'=>'first_name',
			'value'=>'$data->getFirstName()',
		),
		array(
			'name'=>'last_name',
			'value'=>'$data->getLastName()',
		),
		array(
			'name'=>'middle_name',
			'value'=>'$data->getMiddleName()',
		),
		array(
			'name'=>'username',
			'value'=>'$data->getUserName()',
		),
		array(
			'name'=>'role',
			'type'=>'raw',
			'value'=>'CommonFunctions::getLabel($data->role,CommonFunctions::USER_ROLE)',
		),

	),
)); ?>

protected/views/user/update.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	array(
		'name'=>'Users',
		'url'=>Yii::app()->createUrl('user/index'),
	),
	'Update -> id:'.$model->id,

);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl."/js/user-logic.js",CClientScript::POS_END);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/view.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	array(
		'name'=>'Users',
		'url'=>Yii::app()->createUrl('user/index'),
	),
	$model->id,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>View User #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',
		'login_name',
		'first_name',
		'last_name',
		'middle_name',
		'email',
		'password',
		'create_date',
		'create_id',
		'update_date',
		'update_id',
		'status',
	),
)); ?>