protected/models/Article.php
<?php

/**
 * This is the model class for table "tbl_article".
 *
 * The followings are the available columns in table 'tbl_article':
 * @property integer $id
 * @property integer $doctor_id
 * @property integer $active
 * @property integer $approve
 * @property string $title
 * @property string $title_ar
 * @property string $summary
 * @property string $summary_ar
 * @property string $body
 * @property string $body_ar
 * @property string $publish_date
 *
 * The followings are the available model relations:
 * @property Staff $doctor
 */
class Article extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_article';
	}

	const STATUS_APPROVED = 1;
	const STATUS_NOT_APPROVED = 0;

	const STATUS_ACTIVE = 1;
	const STATUS_INACTIVE = 0;
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('doctor_id, active, approve, title, title_ar, summary, summary_ar, body, body_ar', 'required'),
			array('doctor_id, active, approve', 'numerical', 'integerOnly'=>true),
			array('publish_date', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, doctor_id, active, approve, title, title_ar, summary, summary_ar, body, body_ar, publish_date', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'doctor' => array(self::BELONGS_TO, 'Staff', 'doctor_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
					'id' => Yii::t('article', 'model.label.id'),
					'doctor_id' => Yii::t('article', 'model.label.doctor'),
					'active' => Yii::t('article', 'model.label.active'),
					'approve' => Yii::t('article', 'model.label.approve'),
					'title' => Yii::t('article', 'model.label.title'),
					'title_ar' => Yii::t('article', 'model.label.title_ar'),
					'summary' => Yii::t('article', 'model.label.summary'),
					'summary_ar' => Yii::t('article', 'model.label.summary_ar'),
					'body' => Yii::t('article', 'model.label.body'),
					'body_ar' => Yii::t('article', 'model.label.body_ar'),
					'publish_date' => Yii::t('article', 'model.label.publish_date'),
				);
	}

	public function delete(){
		return parent::delete();
	}

	public static function getApproveStatusArray(){
		return array(
			self::STATUS_NOT_APPROVED=>Yii::t('article','Not Approved'),
			self::STATUS_APPROVED=>Yii::t('article','Approved'),
		);
	}

	public static function getArticleStatusArray(){
		return array(
			self::STATUS_INACTIVE=>Yii::t('article','Inactive'),
			self::STATUS_ACTIVE=>Yii::t('article','Active'),
		);
	}


	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('doctor_id',$this->doctor_id);
		$criteria->compare('active',$this->active);
		$criteria->compare('approve',$this->approve);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('title_ar',$this->title_ar,true);
		$criteria->compare('summary',$this->summary,true);
		$criteria->compare('summary_ar',$this->summary_ar,true);
		$criteria->compare('body',$this->body,true);
		$criteria->compare('body_ar',$this->body_ar,true);
		$criteria->compare('publish_date',$this->publish_date,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>5,
			),
		));
	}

	public function getTitle(){
		if(Yii::app()->language=="ar"){
			return $this->title_ar;
		}else{
			return $this->title;
		}
	}

	public function getSummary(){
		if(Yii::app()->language=="ar"){
			return $this->summary_ar;
		}else{
			return $this->summary;
		}
	}

	public function getBody(){
		if(Yii::app()->language=="ar"){
			return $this->body_ar;
		}else{
			return $this->body;
		}
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Article the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ArticleController.php
<?php

class ArticleController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess', // perform access control for CRUD operations
            'checkAdminAccess',
            'checkSideBarSubId +index,create',
            'postOnly + delete', // we only allow deletion via POST request
        );
    }


    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->pageTitle = Yii::t('article', 'Create Article');
        $this->contentTitle = Yii::t('article', 'Create Article');

        if (!isset($_POST['Article'])) {
            $this->updateImagesListJSONFile();
        }

        $model = new Article;

        if ($this->user->role == User::ROLE_EDITOR) {
            $model->doctor_id = $this->user->doctor_id;
        }
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Article'])) {
            $model->attributes = $_POST['Article'];
            $model->active = Article::STATUS_INACTIVE;
            $model->approve = Article::STATUS_NOT_APPROVED;
            if ($this->user->role == User::ROLE_EDITOR) {

                if (intval($model->doctor_id) != intval($this->user->doctor_id)) {
                    throw new CHttpException(400);
                }
            }

            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $this->pageTitle = Yii::t('article', 'Edit Article');
        $this->contentTitle = Yii::t('article', 'Edit Article');
        $model = $this->loadModel($id);

        if ($this->user->role == User::ROLE_EDITOR) {

            if (intval($model->doctor_id) != intval($this->user->doctor_id)) {
                throw new CHttpException(400);
            }
        }
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);


        if (isset($_POST['Article'])) {
            $model->attributes = $_POST['Article'];
            if ($model->save()) {
                $this->redirect(array('index'));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionActive()
    {
        if (isset($_POST['article_id'])) {
            $articleModelId = intval($_POST['article_id']);
            $articleModel = $this->loadModel($articleModelId);

            if($this->user->role==User::ROLE_EDITOR){
                if($articleModel->doctor_id!=$this->user->doctor_id){
                    throw new CHttpException(400);
                }
            }
            if ($articleModel->active == Article::STATUS_ACTIVE) {
                $articleModel->active = Article::STATUS_INACTIVE;

            } else if ($articleModel->active == Article::STATUS_INACTIVE) {
                $articleModel->active = Article::STATUS_ACTIVE;
                //$articleModel->publish_date = date('Y-m-d');
            }
            if ($articleModel->save(false)) {
                $this->redirect(array('article/index'));
            }
        }
    }

    public function actionApprove()
    {
        if (isset($_POST['article_id'])) {
            if ($this->user->role != User::ROLE_ADMIN) {
                throw new CHttpException(400);
            }
            $articleModelId = intval($_POST['article_id']);
            $articleModel = $this->loadModel($articleModelId);
            if ($articleModel->approve == Article::STATUS_NOT_APPROVED) {
                $articleModel->approve = Article::STATUS_APPROVED;

            } else if ($articleModel->approve == Article::STATUS_APPROVED) {
                $articleModel->approve = Article::STATUS_NOT_APPROVED;
                $articleModel->publish_date = date('Y-m-d');
            }
            if ($articleModel->save(false)) {
                $this->redirect(array('article/index'));
            }
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $this->pageTitle = Yii::t('article', 'Articles');
        $this->contentTitle = Yii::t('article', 'Articles');

        $articleModel = new Article('search');
        $articleModel->unsetAttributes();
        if ($this->user->role == User::ROLE_EDITOR) {
            $articleModel->doctor_id = $this->user->doctor_id;
        }
        $this->render('index', array(
            'articleModel' => $articleModel,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Article('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Article']))
            $model->attributes = $_GET['Article'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Article the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Article::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Article $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'article-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function renderArticleOptions($data, $row)
    {
        $this->renderPartial('partials/article-option', array(
            'data' => $data,
        ), false, false);
    }

    public function filterCheckAdminAccess($chain)
    {
        if (!is_null($this->user)) {
            if ($this->user->role == User::ROLE_ADMIN || $this->user->role == User::ROLE_EDITOR) {
                $chain->run();
            } else {
                throw new CHttpException(400);
            }
        } else {
            throw new CHttpException(400);
        }
    }
}

protected/views/article/partials/article-option.php
<div class="visible-md visible-lg hidden-sm hidden-xs">
    <a href="<?php echo $this->createUrl('article/update', array('id' => $data->id)); ?>"
       class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit Article"><i
            class="fa fa-edit"></i></a>

    <form id="deleteForm_<?php echo $data->id; ?>" style="display: inline;"
          action="<?php echo $this->createUrl('article/delete'); ?>" method="post">
        <input type="hidden" name="article_id" value="<?php echo $data->id; ?>"/>
        <a href="#" class="btn btn-xs btn-bricky tooltips" data-placement="top"
           onclick="if(confirm('Are you Sure you want to delete the article?')){$('#deleteForm_<?php echo $data->id; ?>').submit();}"
           data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
    </form>
    <form id="activateForm_<?php echo $data->id; ?>" style="display: inline;"
          action="<?php echo $this->createUrl('article/active'); ?>" method="post">
        <input type="hidden" name="article_id" value="<?php echo $data->id; ?>"/>
        <a href="#" class="btn btn-xs btn-bricky tooltips" data-placement="top"
           onclick="if(confirm('Are You Sure?')){$('#activateForm_<?php echo $data->id; ?>').submit();}"
           data-original-title="<?php echo $data->active == Article::STATUS_ACTIVE ? "deActivate" : "Activate" ?>"><i
                class="fa fa-star fa fa-white"></i></a>
    </form>
    <?php if ($this->user->role == User::ROLE_ADMIN): ?>

        <form id="approveForm_<?php echo $data->id; ?>" style="display: inline;"
              action="<?php echo $this->createUrl('article/approve'); ?>" method="post">
            <input type="hidden" name="article_id" value="<?php echo $data->id; ?>"/>
            <a href="#" class="btn btn-xs btn-bricky tooltips" data-placement="top"
               onclick="if(confirm('Are You Sure?')){$('#approveForm_<?php echo $data->id; ?>').submit();}"
               data-original-title="<?php echo $data->approve == Article::STATUS_APPROVED ? "Don\'t approve" : "Approve" ?>"><i
                    class="fa fa-star fa fa-white"></i></a>
        </form>

    <?php endif; ?>


</div>

protected/views/article/partials/checkbox-column.php
<?php
/**
 * Created by PhpStorm.
 * User: 3mkBurhan
 * Date: 5/3/15
 * Time: 12:43 PM
 */
?>

<div class="checkbox-table">
    <label>
        <?php if($data->active==Article::STATUS_ACTIVE):?>
            <input type="checkbox" name="article_id[]" value="<?php echo $data->id;?>" class="flat-green article-checkbox" checked>
        <?php endif;?>
        <?php if($data->active==Article::STATUS_INACTIVE):?>
            <input type="checkbox" name="article_id[]" value="<?php echo $data->id;?>" class="flat-green article-checkbox">
        <?php endif;?>
    </label>
</div>

protected/views/article/partials/options-column.php
<div class="visible-md visible-lg hidden-sm hidden-xs">
    <a href="<?php echo Yii::app()->createUrl('article/update',array('id'=>$data->id))?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
    <a confirm="Are You Sure You Want to Delete?" href="<?php echo Yii::app()->createUrl('article/delete',array('id'=>$data->id))?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
</div>
<div class="visible-xs visible-sm hidden-md hidden-lg">
    <div class="btn-group">
        <a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
            <i class="fa fa-cog"></i> <span class="caret"></span>
        </a>
        <ul role="menu" class="dropdown-menu pull-right">
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="<?php echo Yii::app()->createUrl('article/update',array('id'=>$data->id))?>">
                    <i class="fa fa-edit"></i> Edit
                </a>
            </li>

            <li role="presentation">
                <a role="menuitem" tabindex="-1" confirm="Are You Sure You Want to Delete?" href="<?php echo Yii::app()->createUrl('article/delete',array('id'=>$data->id))?>">
                    <i class="fa fa-times"></i> Remove
                </a>
            </li>
        </ul>
    </div>
</div>